Transcode: transcode::util Namespace Reference
transcode::util Namespace Reference
Util namespace, all the utility functions and classes are found within this namespace.
Classes
class FfmpegSingleton
A singleton class that provides all the implementations for the FFMPEG functions.
class FFMPEGException
Exception that is thrown if something goes wrong with the FFMPEG library.
class FileException
class File
A class that represents a file on the file system, it can be used to access meta data about the file.
class UtilMediaException
An exception that is thrown from within the MediaUtils functions.
Functions
template<typename T >
std::vector< T > extractMetaData (const AVFormatContext *videoFile, AVMediaType mediatype, std::tr1::function< T(const AVStream &)> metadataCallback)
Extract the media meta data of the given type from the libav AVFormatContext struct using the provided get meta data function.
std::string ffmpegErrorMessage (int errorCode)
Below is the implementation of the public API functions.
AVFormatContext * retrieveAVFormatContext (const std::string &filePath) throw (FFMPEGException)
Retrieve the AVFormatContext for the provided media file.
std::vector< SubtitleMetaData > extractSubtitleDetails (const AVFormatContext *videoFile) throw (FFMPEGException)
Extract the subtitle details from the provided libav AVFormatContext.
std::vector< AudioMetaData > extractAudioDetails (const AVFormatContext *videoFile) throw (FFMPEGException)
Extract the audio detail from the provided libav AVFormatContext.
std::vector< VideoMetaData > extractVideoDetails (const AVFormatContext *videoFile) throw (FFMPEGException)
Extract the video detail from the provided libav AVFormatContext.
ContainerMetaData buildContainerDetail (const AVFormatContext *videoFile) throw (FFMPEGException)
Build a ContainerDetail struct out of the details in the provided AVFormatContext.
void closeCodecs (AVFormatContext *videoFile) throw (FFMPEGException)
Close any codecs that are related to the provided AVFormatContext.
std::vector< SubtitleMetaData > findSubtitleMetaData (const std::string &filePath) throw (UtilMediaException)
Find the subtitle meta data for the media file at the provided path.
std::vector< AudioMetaData > findAudioMetaData (const std::string &filePath) throw (UtilMediaException)
Find the audio meta data for the media file at the provided path.
std::vector< VideoMetaData > findVideoMetaData (const std::string &filePath) throw (UtilMediaException)
Find the video meta data for the media file at the provided path.
ContainerMetaData findContainerMetaData (const std::string &filePath) throw (UtilMediaException)
Find the container meta data for the media file at the provided path.
MediaFileMetaData findMediaFileMetaData (const std::string &filePath) throw (UtilMediaException)
Find the meta data for the media file at the provided path.
template<typename K , typename V >
V get (const std::map< K, V > &map, const K &key)
Convenience template to make it easier to get the value out of a constant map.
Variables
const std::string UNKNOWN = "Unknown"
Detailed Description
Util namespace, all the utility functions and classes are found within this namespace.
Util namespace, all the untility functions and classes are found within this namespace.
You might find something useful here but hopefully everything in the {
See also:
transcode} namespace should provide what you need so you shouldn't have to look in here.
Function Documentation
ContainerMetaData transcode::util::buildContainerDetail (const AVFormatContext * videoFile) throw (FFMPEGException)
Build a ContainerDetail struct out of the details in the provided AVFormatContext.
Parameters:
videoFile - the AVFormatContext that contains the details to be used to populate the ContainerDetail.
Returns:
a populated ContainerDetail struct.
Definition at line 529 of file util_ffmpeg.cpp.
Referenced by findContainerMetaData(), and findMediaFileMetaData().
void transcode::util::closeCodecs (AVFormatContext * videoFile) throw (FFMPEGException)
Close any codecs that are related to the provided AVFormatContext.
Parameters:
videoFile - the AVFormatContext that will have all it's codecs closed.
Definition at line 535 of file util_ffmpeg.cpp.
Referenced by findMediaFileMetaData().
std::vector< AudioMetaData > transcode::util::extractAudioDetails (const AVFormatContext * videoFile) throw (FFMPEGException)
Extract the audio detail from the provided libav AVFormatContext.
Parameters:
videoFile - the av context that contains the media file details.
Returns:
a vector containing audio detail structs populated from values within the media file.
Definition at line 517 of file util_ffmpeg.cpp.
Referenced by findAudioMetaData().
template<typename T > std::vector<T> transcode::util::extractMetaData (const AVFormatContext * videoFile, AVMediaType mediatype, std::tr1::function< T(const AVStream &)> metadataCallback)
Extract the media meta data of the given type from the libav AVFormatContext struct using the provided get meta data function.
Parameters:
videoFile - the av format context that contains the audio meta data to extract.
mediaType - the type of media stream that should have it's codec inspected.
metadataCallback - the function to use to get the correct meta data out of the codec.
Returns:
a vector containing all the extracted meta data.
Definition at line 332 of file util_ffmpeg.cpp.
std::vector< SubtitleMetaData > transcode::util::extractSubtitleDetails (const AVFormatContext * videoFile) throw (FFMPEGException)
Extract the subtitle details from the provided libav AVFormatContext.
Parameters:
videoFile - the av context that contains the media file details.
Returns:
a vector containing subtitle detail structs populated from values within the media file.
Definition at line 511 of file util_ffmpeg.cpp.
Referenced by findSubtitleMetaData().
std::vector< VideoMetaData > transcode::util::extractVideoDetails (const AVFormatContext * videoFile) throw (FFMPEGException)
Extract the video detail from the provided libav AVFormatContext.
@param videoFile - the av context that contains the media file details.
Returns:
a vector containing video detail structs populated from values within the media file.
Definition at line 523 of file util_ffmpeg.cpp.
Referenced by findVideoMetaData().
std::string transcode::util::ffmpegErrorMessage (int errorCode)
Below is the implementation of the public API functions.
Get the FFMPEG message for the provided error code.
Parameters:
errorCode - the FFMPEG error code.
Returns:
the error message that relates to the provided error code.
Definition at line 500 of file util_ffmpeg.cpp.
std::vector< AudioMetaData > transcode::util::findAudioMetaData (const std::string & filePath) throw (UtilMediaException)
Find the audio meta data for the media file at the provided path.
Parameters:
filePath - the path to the file that will have it's details inspected.
Returns:
the audio meta data for the provided media file if possible.
Definition at line 141 of file util_media_ffmpeg.cpp.
References extractAudioDetails(), and findAudioMetaData().
Referenced by findAudioMetaData().
ContainerMetaData transcode::util::findContainerMetaData (const std::string & filePath) throw (UtilMediaException)
Find the container meta data for the media file at the provided path.
Parameters:
filePath - the path to the file that will have it's details inspected.
Returns:
the container meta data for the provided media file if possible.
Definition at line 159 of file util_media_ffmpeg.cpp.
References buildContainerDetail(), and findContainerMetaData().
Referenced by findContainerMetaData().
MediaFileMetaData transcode::util::findMediaFileMetaData (const std::string & filePath) throw (UtilMediaException)
Find the meta data for the media file at the provided path.
Parameters:
filePath - the path to the file that will have it's details inspected.
Returns:
the meta data for the provided media file if possible.
Definition at line 168 of file util_media_ffmpeg.cpp.
References buildContainerDetail(), closeCodecs(), helper::extractCheckedMetaData(), and findMediaFileMetaData().
Referenced by findMediaFileMetaData().
std::vector< SubtitleMetaData > transcode::util::findSubtitleMetaData (const std::string & filePath) throw (UtilMediaException)
Find the subtitle meta data for the media file at the provided path.
Parameters:
filePath - the path to the file that will have it's details inspected.
Returns:
the subtitle meta data for the provided media file if possible.
Definition at line 132 of file util_media_ffmpeg.cpp.
References extractSubtitleDetails(), and findSubtitleMetaData().
Referenced by findSubtitleMetaData().
std::vector< VideoMetaData > transcode::util::findVideoMetaData (const std::string & filePath) throw (UtilMediaException)
Find the video meta data for the media file at the provided path.
Parameters:
filePath - the path to the file that will have it's details inspected.
Returns:
the video meta data for the provided media file if possible.
Definition at line 150 of file util_media_ffmpeg.cpp.
References extractVideoDetails(), and findVideoMetaData().
Referenced by findVideoMetaData().
template<typename K , typename V > V transcode::util::get (const std::map< K, V > & map, const K & key)
Convenience template to make it easier to get the value out of a constant map.
Parameters:
map - the map to get the value out of.
key - the key of the value in the map that we wish to get.
Returns:
the value from the const map that is related to the provided key if it exists, otherwise return an empty instance of the value type.
Definition at line 42 of file util_standard.hpp.
AVFormatContext * transcode::util::retrieveAVFormatContext (const std::string & filePath) throw (FFMPEGException)
Retrieve the AVFormatContext for the provided media file.
This can then be used to extract the files meta data and media streams.
Parameters:
filePath - the path to the media file.
Returns:
the AVFormatContext for the provided media file.
Definition at line 505 of file util_ffmpeg.cpp.